version: '3.4'
networks:
  frontend:
    external: true

services:
    nginx:
        restart: unless-stopped
        image: nginx
        ports:
         - "443:443"
         - "80:80"
        volumes:
         - ./data/nginx:/etc/nginx/conf.d
         - ./data/certbot/conf:/etc/letsencrypt
         - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
         - frontend

    certbot:
        image: j0nnylester/certbot
        restart: unless-stopped
        volumes:
         - ./data/certbot/conf:/etc/letsencrypt
         - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
